sudo: required
services:
  - docker

before_install:
  - docker build -t dzungchu245/react-test -f ./client/Dockerfile.dev ./client

script:
  # - docker run -t dzungchu245/react-test npm test -- --coverage
  - docker run -e CI=true dzungchu245/react-test npm test

after_success:
  - docker build -t dzungchu245/multi-client ./client
  - docker build -t dzungchu245/multi-nginx ./nginx
  - docker build -t dzungchu245/multi-server ./server
  - docker build -t dzungchu245/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push dzungchu245/multi-client
  - docker push dzungchu245/multi-nginx
  - docker push dzungchu245/multi-server
  - docker push dzungchu245/multi-worker

language: generic
